apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: application
      labels:
        app: my-app
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: application
      labels:
        app: my-app
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: application:latest
      source:
        git:
          uri: https://github.com/appuio/example-php-sti-helloworld.git
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: php:7.3
            namespace: openshift
        type: Source
